ARCH_LIBS :=
ARCH_CFLAGS :=
MICRONDK_TARGET_CFLAGS := $(ARCH_CFLAGS) $(LOCAL_CFLAGS) $(CFLAGS)

PROJECT_OUTPUT ?= $(LOCAL_MODULE)

$(PROJECT_OUTPUT):
	INCLUDES="$(LOCAL_C_INCLUDES)" SOURCES="$(LOCAL_SRC_FILES)" CFLAGS="$(MICRONDK_TARGET_CFLAGS)" CPPFLAGS="$(LOCAL_CPPFLAGS)" sh $(MICRONDK_DIR)/gen/$(GENERATE)/gen.sh $(PROJECT_OUTPUT)
